[package]
name = "linkndrop"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.11.0"
once_cell = "1.21.3"
rand = "0.9.1"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
sled = "0.34.7"
